# Site settings
title: Aaron Benjamin - Digital UX Designer
description: Aaron is a digital UX designer with happy clients around the world. Aaron's been designing websites, apps, and other digital products for over eight years and is focused on personalized service.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atlantadesign.ninja"

# Build settings
markdown: kramdown
port: 8000
sass:
  sass_dir: assets/css
  style: :nested