"""Build non-destructive WebP delivery variants. Requires Pillow; originals stay intact."""
from pathlib import Path
import json
import re
from PIL import Image, ImageOps

repo = Path(__file__).resolve().parent.parent
sources = list((repo / 'src').rglob('*.pug')) + list((repo / 'src/prototypes').rglob('*.ts'))
refs = set()
for source in sources:
    refs.update(re.findall(r'(?:/?assets/img/)[^\s\"\'<>]+?\.(?:png|jpg|jpeg)', source.read_text()))
# Product images are referenced through category/row IDs at runtime.
for directory, pattern in [('project--price-adjustments', 'product-*-transparent.png'), ('project--green-loom/products', '*.png')]:
    for source in (repo / 'src/assets/img/folio' / directory).glob(pattern):
        refs.add('/' + str(source.relative_to(repo / 'src')))
manifest = {}
for ref in sorted(refs):
    url = '/' + ref.lstrip('/')
    original = repo / 'src' / url.lstrip('/')
    if not original.exists():
        continue
    with Image.open(original) as source:
        image = ImageOps.exif_transpose(source).convert('RGBA' if 'A' in source.getbands() else 'RGB')
        if image.width < 240:
            continue
        widths = sorted(set(min(w, image.width) for w in (240, 480, 800, 1100, 1600)))
        variants = []
        for width in widths:
            output = original.parent / 'responsive' / f'{original.name}-{width}.webp'
            output.parent.mkdir(exist_ok=True)
            height = round(image.height * width / image.width)
            image.resize((width, height), Image.Resampling.LANCZOS).save(output, 'WEBP', quality=92, method=6)
            variants.append({'src': '/' + str(output.relative_to(repo / 'src')), 'width': width})
        manifest[url] = {'width': image.width, 'height': image.height, 'variants': variants}
(repo / 'src/includes/image-variants.pug').write_text('//- Generated by scripts/build-image-variants.py; do not edit.\n- const folioImageVariants = ' + json.dumps(manifest, separators=(',', ':')) + '\n- const folioSrcset = src => (folioImageVariants["/" + src.replace(/^\\//, "")]?.variants || []).map(image => `${image.src} ${image.width}w`).join(", ") || undefined\n')
(repo / 'src/assets/data/image-variants.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(f'Built responsive delivery variants for {len(manifest)} referenced originals; originals unchanged.')
