#!/usr/bin/env python3
"""Generate host discovery adapters from canonical agents and skills.

Canonical sources remain agents/*.md and skills/*. Generated files under
.agents/, .claude/, .cursor/, .github/, .windsurf/, and CLAUDE.md must not be
hand-edited.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

POINTER_BODY = """\
# Many Hats

This repository packages a portable AI product team.

1. Read [`AGENTS.md`](AGENTS.md) for routing, human authority, and knowledge hierarchy.
2. Load only the agent definition in `agents/<name>.md` that matches the request.
3. Load only skills whose frontmatter descriptions match the request from `skills/` (or the host skill mount).
4. Read relevant project knowledge before inventing domain facts.
5. Preserve human authority for consequential choices and external actions.

Start with Liza when the request spans multiple product disciplines.
"""

WINDSURF_RULE = """\
---
trigger: always_on
description: Many Hats routing contract pointer
---

# Many Hats

Read `AGENTS.md` for routing, human authority, and knowledge hierarchy.
Load only the matching `agents/<name>.md` and skill packages under `.agents/skills/`.
Do not invent domain facts; read project knowledge first.
Preserve human authority for consequential choices and external actions.
"""

BRING_IN_WHEN: dict[str, str] = {
    "liza": "Direction, priority, scope, requirements, tradeoffs",
    "luke": "Objects, states, rules, permissions, domain consistency",
    "charlie": "Journeys, IA, flows, wireframes, usability",
    "iris": "Components, visual hierarchy, interaction patterns, tokens",
    "finn": "Production implementation and technical decomposition",
    "sentry": "Failure modes, test strategy, regressions, release readiness",
    "scout": "Research questions, evidence collection, synthesis, confidence",
    "cipher": "Threats, trust boundaries, sensitive data, privacy controls",
    "ledger": "Metrics, events, experiments, reporting grain",
    "echo": "UI terminology, labels, instructions, voice, comprehension",
    "relay": "APIs, contracts, external systems, degraded behavior",
    "harbor": "CI/CD, observability, SLOs, rollback, incidents",
    "allie": "Independent challenge before commitment or release",
}

ALL_HOSTS = ("claude", "cursor", "codex", "copilot", "windsurf")
GENERATED_MARKER = "<!-- Generated by scripts/generate_adapters.py. Do not edit by hand. -->\n"


@dataclass(frozen=True)
class AgentDef:
    name: str
    description: str
    primary_skills: list[str]
    body: str
    source_path: Path


def parse_frontmatter(text: str) -> tuple[dict[str, object], str]:
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("unterminated YAML frontmatter")
    raw = text[4:end]
    body = text[end + 5 :]
    data: dict[str, object] = {}
    current_key: str | None = None
    for line in raw.splitlines():
        if not line.strip():
            continue
        if re.match(r"^[a-zA-Z0-9_-]+:", line):
            key, _, value = line.partition(":")
            current_key = key.strip()
            value = value.strip()
            if value.startswith("[") and value.endswith("]"):
                inner = value[1:-1].strip()
                data[current_key] = [item.strip() for item in inner.split(",") if item.strip()] if inner else []
            elif value:
                data[current_key] = value
            else:
                data[current_key] = []
        elif line.startswith("  - ") and current_key is not None:
            items = data.get(current_key)
            if not isinstance(items, list):
                items = []
                data[current_key] = items
            items.append(line[4:].strip())
        else:
            raise ValueError(f"unsupported frontmatter line: {line!r}")
    return data, body.lstrip("\n")


def load_agents() -> list[AgentDef]:
    agents: list[AgentDef] = []
    for path in sorted((ROOT / "agents").glob("*.md")):
        if path.name == "README.md":
            continue
        data, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        name = str(data["name"])
        description = str(data["description"])
        when = BRING_IN_WHEN.get(name)
        if when and "Use when" not in description:
            description = f"{description} Use when: {when}."
        primary = data.get("primary_skills", [])
        if not isinstance(primary, list):
            raise ValueError(f"{path}: primary_skills must be a list")
        agents.append(
            AgentDef(
                name=name,
                description=description,
                primary_skills=[str(item) for item in primary],
                body=body.rstrip() + "\n",
                source_path=path,
            )
        )
    return agents


def skill_dirs() -> list[Path]:
    return sorted(path.parent for path in (ROOT / "skills").glob("*/SKILL.md"))


def yaml_escape(value: str) -> str:
    if re.search(r'[:#\[\]{}",\n]', value) or value.startswith(("*", "&", "!", "|", ">", "%", "@", "`")):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def write_text(path: Path, content: str, *, dry_run: bool, planned: list[str]) -> None:
    rel = path.relative_to(ROOT).as_posix()
    existing = path.read_text(encoding="utf-8") if path.exists() and path.is_file() else None
    if existing == content:
        return
    planned.append(f"write {rel}")
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def link_skill(target: Path, skill_dir: Path, *, dry_run: bool, planned: list[str]) -> None:
    rel = target.relative_to(ROOT).as_posix()
    relative = os.path.relpath(skill_dir, start=target.parent)
    if target.is_symlink() or target.exists():
        if target.is_symlink() and os.readlink(target) == relative:
            return
        if target.exists() and not target.is_symlink():
            raise RuntimeError(f"Refusing to replace non-symlink: {rel}")
    planned.append(f"link {rel} -> {relative}")
    if dry_run:
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink() or target.exists():
        target.unlink()
    try:
        target.symlink_to(relative)
    except OSError:
        # Fallback for environments that cannot create symlinks.
        if target.exists() or target.is_symlink():
            target.unlink()
        target.mkdir(parents=True, exist_ok=True)
        stub_path = target / "SKILL.md"
        stub = (
            "---\n"
            f"name: {skill_dir.name}\n"
            f"description: Many Hats skill mount stub. Read skills/{skill_dir.name}/SKILL.md.\n"
            "---\n\n"
            f"# {skill_dir.name}\n\n"
            f"This host could not create a symlink. Read the canonical skill at "
            f"`skills/{skill_dir.name}/SKILL.md`.\n"
        )
        planned.append(f"write {stub_path.relative_to(ROOT).as_posix()} (symlink fallback)")
        stub_path.write_text(stub, encoding="utf-8")


def ensure_skill_links(mount: Path, *, dry_run: bool, planned: list[str]) -> None:
    for skill_dir in skill_dirs():
        link_skill(mount / skill_dir.name, skill_dir, dry_run=dry_run, planned=planned)


def nested_agent_body(body: str) -> str:
    """Rewrite avatar links from agents/ (../avatars) to host agent dirs (../../avatars)."""
    return body.replace("](../avatars/", "](../../avatars/")


def render_claude_agent(agent: AgentDef) -> str:
    lines = [
        "---",
        f"name: {agent.name}",
        f"description: {yaml_escape(agent.description)}",
        "skills:",
    ]
    for skill in agent.primary_skills:
        lines.append(f"  - {skill}")
    lines.extend(["---", "", nested_agent_body(agent.body).rstrip(), ""])
    return "\n".join(lines)


def render_cursor_agent(agent: AgentDef) -> str:
    return (
        "---\n"
        f"name: {agent.name}\n"
        f"description: {yaml_escape(agent.description)}\n"
        "model: inherit\n"
        "---\n\n"
        f"{nested_agent_body(agent.body).rstrip()}\n"
    )


def render_copilot_agent(agent: AgentDef) -> str:
    return (
        "---\n"
        f"name: {agent.name}\n"
        f"description: {yaml_escape(agent.description)}\n"
        "---\n\n"
        f"{nested_agent_body(agent.body).rstrip()}\n"
    )


def render_pointer(title_path: str) -> str:
    # Relative markdown links differ by depth; use plain paths in pointer bodies.
    body = POINTER_BODY.replace("[`AGENTS.md`](AGENTS.md)", "`AGENTS.md`")
    return GENERATED_MARKER + body


def expected_paths(hosts: set[str]) -> set[Path]:
    paths: set[Path] = set()
    skills = [path.name for path in skill_dirs()]
    agents = [path.stem for path in (ROOT / "agents").glob("*.md") if path.name != "README.md"]

    if hosts & {"cursor", "codex", "copilot", "windsurf", "claude"}:
        # Shared skill mount for hosts that scan .agents/skills.
        if hosts & {"cursor", "codex", "copilot", "windsurf"}:
            for name in skills:
                paths.add(ROOT / ".agents" / "skills" / name)

    if "claude" in hosts:
        for name in skills:
            paths.add(ROOT / ".claude" / "skills" / name)
        for name in agents:
            paths.add(ROOT / ".claude" / "agents" / f"{name}.md")
        paths.add(ROOT / "CLAUDE.md")

    if "cursor" in hosts:
        for name in agents:
            paths.add(ROOT / ".cursor" / "agents" / f"{name}.md")

    if "copilot" in hosts:
        for name in agents:
            paths.add(ROOT / ".github" / "agents" / f"{name}.agent.md")
        paths.add(ROOT / ".github" / "copilot-instructions.md")

    if "windsurf" in hosts:
        paths.add(ROOT / ".windsurf" / "rules" / "many-hats.md")

    return paths


def generate(hosts: set[str], *, dry_run: bool = False) -> list[str]:
    planned: list[str] = []
    agents = load_agents()

    shared_hosts = hosts & {"cursor", "codex", "copilot", "windsurf"}
    if shared_hosts:
        ensure_skill_links(ROOT / ".agents" / "skills", dry_run=dry_run, planned=planned)

    if "claude" in hosts:
        ensure_skill_links(ROOT / ".claude" / "skills", dry_run=dry_run, planned=planned)
        for agent in agents:
            write_text(
                ROOT / ".claude" / "agents" / f"{agent.name}.md",
                render_claude_agent(agent),
                dry_run=dry_run,
                planned=planned,
            )
        write_text(ROOT / "CLAUDE.md", render_pointer("CLAUDE.md"), dry_run=dry_run, planned=planned)

    if "cursor" in hosts:
        for agent in agents:
            write_text(
                ROOT / ".cursor" / "agents" / f"{agent.name}.md",
                render_cursor_agent(agent),
                dry_run=dry_run,
                planned=planned,
            )

    if "copilot" in hosts:
        for agent in agents:
            write_text(
                ROOT / ".github" / "agents" / f"{agent.name}.agent.md",
                render_copilot_agent(agent),
                dry_run=dry_run,
                planned=planned,
            )
        write_text(
            ROOT / ".github" / "copilot-instructions.md",
            render_pointer("copilot-instructions.md"),
            dry_run=dry_run,
            planned=planned,
        )

    if "windsurf" in hosts:
        write_text(
            ROOT / ".windsurf" / "rules" / "many-hats.md",
            GENERATED_MARKER + WINDSURF_RULE,
            dry_run=dry_run,
            planned=planned,
        )

    return planned


def check_adapters(hosts: set[str] | None = None) -> list[str]:
    """Return human-readable errors if generated adapters are missing or stale."""
    selected = set(hosts or ALL_HOSTS)
    errors: list[str] = []

    planned = generate(selected, dry_run=True)
    for item in planned:
        errors.append(f"stale or missing adapter: {item}")

    for path in expected_paths(selected):
        rel = path.relative_to(ROOT).as_posix()
        if path.parent.name == "skills" and path.parent.parent.name in {".agents", ".claude"}:
            if not path.exists() and not path.is_symlink():
                errors.append(f"missing skill mount: {rel}")
            elif path.is_symlink():
                target = (path.parent / os.readlink(path)).resolve()
                if not (target / "SKILL.md").exists():
                    errors.append(f"broken skill mount: {rel}")
            continue
        if not path.exists():
            errors.append(f"missing adapter file: {rel}")
            continue
        if path.suffix in {".md"} or path.name.endswith(".agent.md"):
            text = path.read_text(encoding="utf-8")
            if path.name in {"CLAUDE.md", "copilot-instructions.md", "many-hats.md"}:
                if "AGENTS.md" not in text:
                    errors.append(f"{rel}: pointer must mention AGENTS.md")
                continue
            data, _ = parse_frontmatter(text)
            if "name" not in data or "description" not in data:
                errors.append(f"{rel}: missing required name/description frontmatter")
            if ".cursor/agents" in rel and data.get("model") != "inherit":
                errors.append(f"{rel}: Cursor agent must set model: inherit")
            if ".claude/agents" in rel:
                skills = data.get("skills")
                if not isinstance(skills, list) or not skills:
                    errors.append(f"{rel}: Claude agent must declare primary skills")
    return errors


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--claude", action="store_true")
    parser.add_argument("--cursor", action="store_true")
    parser.add_argument("--codex", action="store_true")
    parser.add_argument("--copilot", action="store_true")
    parser.add_argument("--windsurf", action="store_true")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true", help="Exit 1 if adapters are missing or stale")
    return parser.parse_args(argv)


def selected_hosts(args: argparse.Namespace) -> set[str]:
    hosts: set[str] = set()
    if args.all:
        return set(ALL_HOSTS)
    for host in ALL_HOSTS:
        if getattr(args, host):
            hosts.add(host)
    if not hosts:
        return set(ALL_HOSTS)
    return hosts


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    hosts = selected_hosts(args)
    if args.check:
        errors = check_adapters(hosts)
        if errors:
            for error in errors:
                print(f"ERROR: {error}", file=sys.stderr)
            return 1
        print(f"PASS: adapters current for {', '.join(sorted(hosts))}")
        return 0

    planned = generate(hosts, dry_run=args.dry_run)
    if args.dry_run:
        if not planned:
            print("dry-run: adapters already current")
        else:
            for item in planned:
                print(item)
        return 0

    print(f"generated adapters for {', '.join(sorted(hosts))} ({len(planned)} changes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
